apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:xRJ5obpDo/a3v8CLTxGHNZ7qBgGXvumGu2G1nujZbIXexgrCiyyO2FEcmKb3xUQLKO5QeMmRQcXM17tf8PYbd5fZBYG1qwoWxe3qWAtln4q7MAeT11URV5cYy8KlXiOzr/KMNLresqyVc4DTvFznP3FQVYfkhFT9ue+r1sBk9W2IyONUmgJXrPGafTzi+kVXPcXNzB3X4vzrwLd7+Nt9sbqFRcH5dreuQhAldQhbzj6U26AWqL7zotBUN/NEI2E67DzEdrF31v1tGe0JDC/QZg9vAt8riQnusMqrQaMXR7qLBOf99OkVNUWQAegBv1m+3JX1INbHC6hzRPsuqT6cFVeQ2TrZpqCj6ul6fgIQepSlFy6X6NW7EuqeEuyVf44v,iv:cPEDn4pKfkwaL3mwqLud/4/lE8ofaqdaBNUawBganrs=,tag:mFK4UvX76dqskKqnIU1RlQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Ofam/gSdNFL6E6GB65LywOjBCsDc4CuQ1JjASWMnWQOXGVxZvaOSdg/AeGLlA3v2UxOpE1DahnWqAzx8CbY3/IqnDHD4q2+OJNGeR8dUbu9VvLR1BS0fukdrSHZy9l2bAi4YXeV4dbA5Kq0Xd64qGGri8hIUjtc7KkZr0bo2Vv8UJpNBbIFPCAvI7JA2o7aEGqvye9VDXJ9Iv/glevdywf1BuV2dWB9WNARsG0jrApf86GYZKmfLrgTtnEL9/uz+hVOoKUaO7z5IMcvJZQ==,iv:uKuC0MEtLmoOjYnSrJyIjSIj6Ers+sstGiju5xQHbSQ=,tag:6/ruB7cllvWCOrb0J2LdHg==,type:str]
    known_hosts: ENC[AES256_GCM,data:/sAjYtbDH8nIq4qOrV4chTZ+v63v6euZc+cQ+58cokFWByScpwJoic9zQxfe4CnSI4KuofHDuumefw6FaCnStFQ6D9Dx9pbw0Srrz/fNTfmiajHbqZXwv4RKg0NMliHjLDFAd5HjqXFYnA8VjFPRpylh6ceGVO1JneOmX71t7MZRRnwdpnaxNc1szw9sbefi7pwbsXoauq+FoV5fxqyHVEUUv62OGR6IrUn0,iv:goKCMKBavt3HMaF8ddgzaKoBqvmCVofR3DMV/5ErVKc=,tag:6NjDi5FQFhvzjDLnAOMXBw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age18pglxfcmalplgnkpzg5v7mg9mqjwkmmc8gxjecat4j5mp5qtpgsqj6x9kq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZWVuMmordEQ3dE0wVktN
            K000MDhxTmVubklYSGtGc3BUOTBUdm9Zc2xRCnBPbVV1YUFsVDZmTEZsd3d5b2RX
            L0Z1aVFmcDJpRnRXUkJGRzdOWmFIYVkKLS0tIFd5KzhyRFhYekliZnk5SlFMei9D
            UnJNZWJMWVhnQWtVYXNxVjJ6Mk9GQ2cKO4h97H1bgtYEB7TDf6ZUhUwed3AzEvVQ
            4AbFdXQamzENiFypp12TtEoyGluEf7q78bmHFYJ/XV7E4vaprPtR1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T22:10:56Z"
    mac: ENC[AES256_GCM,data:OVxW3goxV35oYofaSKzDd3oCRMjN66hH2xQ96keBG2NYCeuQX3zsDWqLqLYgUkuc43fe4UB8jZQjUjabXVBg3Kmb8b+0Yr354yNKskGEoXg5ZbCDzvHg7EsvDweMUOnVCxpcxtPUuFkqZKoVU3ZtgAJ/PnjEj7P3K4o/2PQmKp8=,iv:psRogOeIUW7aQI7xMYR2kjPzUrwlthylcjFkKDQ/39Q=,tag:NLa5T6OrEi7/bGVdARev5w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
