apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Fnxmhw7bPZP8OtGDQdPx+84rPihY0Erv0PBG+Cmm3jNvt5Ybh5bGo680i2QwfwQ6dsBXUmGBeIziMN++gQ8i/pOHbXGH847OmDhjbTI+/bKjN0SMmGbUl8x952jVn2royKMf6uMaUrhVUUPZWXac/7+Q1Gy7mPzjssbCMxMrxIYa5jVnFo2FgOBYn95lu540Kgfqf9TT97pRCfssEnYH+t8nMptedHod1jYMlz0na4ImaYeHMKDqAGIHsjeKF/QpDH44I8C2YDF31quFx7maa6rlK0feZxt11Xq+C3NL+xQIkdP11SRnRHzjmtYO+pvvGu1XoFWLUFRwx7FZehctIrf/+6mN/3sbAXRCv1BQUWl8x4W8vwyIY8pZqPcNqV1g,iv:kaT07VTQYehFlp4xEtfal9j1wY/7ZwBd41O1DMk+1U0=,tag:/VzMnNWknIr2btL7z3tBYg==,type:str]
    identity.pub: ENC[AES256_GCM,data:qNP5Y8YAyJ5qOe5n60NgwJSRwEmJdWjRGVDTFWvoj40UaNYFUtJGbZanu3bmoxGqfUtWtTPmP+Y9TcZie2KmmDSLSyg6OkFy2detrfdeI292uyDOYVOOR+3dBqINB5JST7vEySzX2zVaOOYlKPfPNb40Gtoz6PCHfrTvmRvUpllyyBCsPPC6TWeQXWUlR3lfTEurNqrmKIo8lAbXlYcVaT3W3XwLeG0ykWJTBq4wx7x4G1EY5fNEVD5bRYh/OEV1+3u4ZeOF9qAoijhphg==,iv:kKTOvC1OTowAKXvDhv6GpU86nioQcqs18p7cnAbPkSg=,tag:HApOhaYWL5s4YOGIqyWIHw==,type:str]
    known_hosts: ENC[AES256_GCM,data:rPNO4BsmJ4EPcTMBz8MUx8u3RzGrZbArcoM5RMteExqWH2DDsIf5Oyo6+vlRuKtxAvL/Cp46KXpsgK78+j8HEm/vXT+qV4hh9EwpQ5lMvwCDpCY+A8aTwwKmdUyKfaxE2UtC7C8OW9sauwmvqT1kqNU3sW0uBU7Tsmzg3JeSc8JuJhOg324cpWyfFzyT4XWSEJQtJupUxNYpF6EN59GfXxBEoGOal5PJWeVP,iv:z/Jx78sXHIJZ8a5On+d5Zp/LWfJbd8v7ajg7MyNt1yc=,tag:ph1Bp6ogAfE1JKNZfu6/VA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age18pglxfcmalplgnkpzg5v7mg9mqjwkmmc8gxjecat4j5mp5qtpgsqj6x9kq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bzBkUHdPVzdzdWgzRVNU
            ajl5c3QxMlp2L21yWkVxLzVaV2JpeXRuYXdRCmo4UXo2ZVN0ZFRmV2pqSlRpMGpo
            U0lsZjcwZE9pMHNUVFZyeEdGWUtzZjQKLS0tIG5iOWM2YnFIWXJySFZSOWJxOFN3
            cDZaaDJQNmpqRVdZcnFnREdac0NYZTAKxBcrZywJiH4JPZgoM4+PCrmYNgchkQgr
            XFZq/uqNDUK21tnObArlrplZuxd8wzw+GUrL2lrxirYZiKQfM+OtkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T17:13:08Z"
    mac: ENC[AES256_GCM,data:cYQrUaD1IItFYExtTnHqMAdpXRUNinAfcc9zIcw2EsAzon/xzjfGv7iRBAKMAasY+syulLbRZC5zg4LvXWQJAL4W6o8ckHtHDew+326uGd+IYIH5v4sNkvHextu1CvOwegI9MxMtpJ+i1dARVMKxQZiJamJ0Sbp7LHSMFbt7+8Y=,iv:pt8rUT1iD0FVQZYMHuPO6/wPCW76r1tZhpqcSvfOJDU=,tag:SQXEHJe5qTAT9sx1lyoZkw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
