apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Smd9wPiukvVIBPqATISvJPqMDl3xQZjjJev8M0qtq9x1DNvms7Zjr2LNnLwZbQOcgd6yIx8ZyOXQChGkLBfD8Zif3kfQN0HY/nVWdAWloZhou+JxjuL0/qVMkv5GDP8Ene34h3jVyOpVz+PTPV2qnyPkTtQ1YzXS3VddiZVCGDitIawTEpdLZnKEXIDppZ5OeZ2oM76rtojQRitIlislB7W5pjNQBpMEjhImLpnrCQmC6h4FfiO3ei5CVMf3JL+3kNfKAivRZlh1q1AnprptuvMZvVKrl8exdCaRCQ1rL+FCDd82EelQVp4LZ19FFEun6G5jPlts5m3oC/BK9mwxHuwWrQJkUNvkWDcxKEOCGl7QVfBAyf5WPOWU0Tk6NQzX,iv:PjLXeAY03YoN9KbUlEd7opAb+rBuLRhwJ5mqZmJ7vJY=,tag:GNaYRUzbyJhqHdWPf7LF7g==,type:str]
    identity.pub: ENC[AES256_GCM,data:Qsto8wuOpcKAgESCNy9rZEqMMG+AuhGoAEU/oONInCSqTutI35N6CxdKP3qm7DsGz+fuHR0c13AEiTYUlBtA55x35BsP6bpRRtNumCShplvs0zIbZrkqlvsPcw4kN6L8krNAhH7s9Z/isOanNowsMgX1ZIDic/4X7vQhin05Q8nFPIfdtrMbb0F/E/SeicP24ydKZDQwahSyKzFJoHmdmUPIk85gS5CxY+8EzYLZHX93NPbMTlZS4kqxDRt0vRLWtBB2cpENia26r75+5g==,iv:9Yk2I2+BJkhK6lVRzxXv3hX5BdIkn9lHLPYgD/C7M6g=,tag:U0PAN5BgkXefa/74X4b7+w==,type:str]
    known_hosts: ENC[AES256_GCM,data:sYuXoJXdEj8t4hmAx0XVd8gztoVioMxKcuxWdn8B2rWzpLcchoA0IDq9ddkvYt9DN30IPLGOrQl9Sy97eIP0Z9Y4YIALmVh5VEFrMsB/HEJNOIOKKlzPxuTjUBH5uORVCMHwwW1iLErYMPk5aSgy8otkR4ald6ypZSnH4DLbruHD2WSaIGfGHL/2qy5ljQgKHNZYd6aA8fiivgnaZdxibEAjoM/Xki4l5rpu,iv:VwPH9/Kf56g//u07WSGMbYkTfig+WJfTRxI6br1+VrI=,tag:Xk121LFUfd5oxo4bZ44FYQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age18pglxfcmalplgnkpzg5v7mg9mqjwkmmc8gxjecat4j5mp5qtpgsqj6x9kq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Q2hnZzJmZEhNd3lmdWI2
            RjY2b0RxVklCbjJHTWx5VHlLalpxY0hzckRvCmRaNzM4Sm9XSkYxK2RZaGVhU0FL
            R2dsQ0F5ekNnbkxHeGgwTkhpMmd5b0UKLS0tIFdYWkl0b0ROY3V4RzlLU05iQ3hx
            M2F5cFNWNnZCUFhoTWwrMVpUcFNMYkEKYtMcj76TLExNPJJ20iT9gHUd4EyTebiv
            HEo/3unVfmu74Zep60b+bN4cN4mFHuECawUSeJe60B2SjG4JCzy6xQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T17:04:30Z"
    mac: ENC[AES256_GCM,data:VS32af+TUzO8Q2G/1OrK4HI/U5SeQ/GPhI4f3vqGcpRVM2PRFNCFbPneLg1HTiuKFHInIZoqWRAvVXSulJ524FczDsrOHY3QryG6gYUgpWwumiSWVwBlL1noJLpdtvtBnVOMcBnH80FgvGWCZ1Jv6sn/VXfb5YSJG2+n7KH6zSs=,iv:mrZQ+ItMm1dF4WoUcVfKs72vXJVx2Wxrjn2At6o85i4=,tag:L/wGCppNRem16ijzXG3RQA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
