apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:nWCkyFLQ1/qKuhdn/4JKo2dS3mukf5UCY+bvsp26qtyZfuziUxeyhRPJHyI8PS08P4RXrmRuNhvKiegqEd6CUee17RLyB8xMGXkbuTDu89VZc9MFI4WpM6e321qlm0dlbYw0dUu/pAaMJ100ifQyDoZcYAB3DB8GNq5e+HkHj28c1y6ghtd5UsmVob7GuMVEO6TCnWl5hNkPAm1axF+Y6dyp8ib0Y1dP7JQI+9csBa97cpA3XfosMS4JQM/zBhPaHsqNQW5vMF7BXnxudR6/b1QopX8JfkegfNn9R+WsyAHErNRYEWbAIlYhfw3vAYNGSJxvqF2QSveKgfK71nERvvLj12RGQFYnKZEToDrSuE7a/E9mUvd3d6HG+Zzlsys1,iv:iapcJVD6qw3LjCQOBx/nKRZkvo9caZedJAYAmQaiTIE=,tag:GPl7ea+IYl36lyDnr2SJQA==,type:str]
    identity.pub: ENC[AES256_GCM,data:t+vahYh31nkbY5Dnk0Rci4SnnuGK/cNQ/KtYp82A6Si9pnCrjBVNkiHPib2caES5n+p3UagB/vatA3nO16jg07+ysgEkVQTy2Ap5yWmCp5b4HjakdUSKzBKCTpPDI44HPsp1cmtlNCW+bqqV36VgfeYrQNITFeqbaRSGsna9IM1AxftBmAKB5e93OedBE3m6DT5OFHl8SQ1makv9h8nVL6SDDT2W+tcpPUfKiyo86jcGqLK/P/NlPPo+MMoE+UBJL1Gi2rpd7tmgjip57A==,iv:IlEn0YqEWrI8M8CWXEBkCW+O89vpMEZvotX5hNY3qUQ=,tag:JmWkqIxmO0bKuXR/ihFAig==,type:str]
    known_hosts: ENC[AES256_GCM,data:KlKct0z6ZrAcjLPKVdWcspexCv4s2msYNveLfiKNxi8wPlBPus428tFfWpiml8JRrtfrHFZhLtao+IGQjDXNxe0db1P+/2t0n23Chn35LzDZim3bJqON4byjwZR1l3osxxXdmqgzZ3x3Frz6igdRkAKu20Z4NGcATaGppqdvDRZpFfmMyNSwUtVHh7k6ArsfVXNNhlM3Y19AFFsXTZX6HWOH6yFA/+q+vQpS,iv:KVUaZpKQDc3EkRANEQNPOFeyB3Q/kQY5xX381m9r7Pc=,tag:KxRca0MPf6qhbSfFN8q55g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age18pglxfcmalplgnkpzg5v7mg9mqjwkmmc8gxjecat4j5mp5qtpgsqj6x9kq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSYXNEYjM3YlJMcWd4WTVL
            c3NaRFUwMDBXU1BxTHBpYjgwUStMU3l5ZUdvCmZCRkx6ZWg1SGlHOU5sMzJCcWdN
            NkVZTHZKS1BtekhGZklqaW05bTZ1ZWMKLS0tIGdHU3JiT21JRTE3Q0tzTWkyWG5J
            WURWc25nMjNrMWlWc1JmenRZTDBSbXcKyVErIR6zR2+/a41D3D1RjbJ0GFnTHi3P
            oKEGOk5VaX/BRr403peBFCV7vWWvUVZkUx3VmNYmZx7VMTjn6IxPPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T16:27:05Z"
    mac: ENC[AES256_GCM,data:l5GZPVCCOIagui2EtSVBcv1MpNLRJd4b/nCYGC4cAY0PObhgZ1KlBhvdPqt5B3y5nn+zyOMhb4Q47eSXM//Gj3A7WXZPNqMv8EPl/c7EX6OYpVvMnfsiXZH7cULkeLBe70NMpFWu/CJ7mvJVhZPCv1CtKhUQDt9R0tiRry14E2Q=,iv:tMruDEfCX12LRffwL9r3Y5S/N255KazPc+Po6YZfzws=,tag:2lSpkbUPD98x3m/oK2qX5w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
