apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: testing
  namespace: testing
spec:
  interval: 15m
  timeout: 20m
  chart:
    spec:
      chart: app-template
      version: 15.4.9
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: testing
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    release_name: testing
    global:
      stopAll: false
    image:
      repository: busybox
      pullPolicy: IfNotPresent
      tag: stable@sha256:303337d3d52898b33018796d760d3a01c2dcc87973dd66ec22fe78ae1e8429c9
    service:
      main:
        enabled: true
        ports:
          main:
            enabled: true
            port: 3000
            protocol: http
    persistence:
      test:
        enabled: true
        type: pvc
        mountPath: /var/lib/test
      my-secret-persistence:
        enabled: true
        type: secret
        objectName: testing-app-template-my-secret
        expandObjectName: false
        mountPath: /var/lib/my-folder
        # subPath: my-file.txt
        # items:
        #   - key: key1
        #     path: my-file.txt
    secret:
      my-secret:
        enabled: true
        data:
          key: "this is my secret value"
          key2: "other key value"
    workload:
      main:
        podSpec:
          containers:
            main:
              command:
                - "sh"
                - "-c"
                - "while true; do sleep 6000; done"
              probes:
                liveness:
                  enabled: false
                readiness:
                  enabled: false
                startup:
                  enabled: false
    addons:
      codeserver:
        enabled: true
        service:
          type: LoadBalancer
