apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:X7FJLm0gKRzUKHszj+ZzijLIxZ0=,iv:ZxCHORsLTYg7lDcvoV8L1kR14clY4qf/pMDP3dcHZqw=,tag:tUqUQuGKwlq5y+i5KM0Ycw==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:ohOE4/lBbTDVN6xe6mDsOCp12mWnuhc5,iv:h0r6Ew6UcmndQG+HP/jyZcLgJDoDzDC7uNz+4o5yOok=,tag:idlkHEDNgAi5tpi61tB7kw==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:S+QPzTBWPBelvdoP4EBlN/ACuEIyfRdu,iv:qceJVzK+b6XQkA5S1bwUt9aPSr7NIKv5xJ8BZ1bI+EI=,tag:KrbI67pzEu8+cVQ2DOZ1ig==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age18pglxfcmalplgnkpzg5v7mg9mqjwkmmc8gxjecat4j5mp5qtpgsqj6x9kq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZDMzZDRIU1hOTldGWktD
            bUxpMDE5ZEZBOXFHUHhHUjhsdDJjby9CbVJZCkZ0eFc2ZzdSd3pQR09URTdlRk05
            d1hPSGh2S1doNk5lVm1LTi9UT0VuZXcKLS0tIEN3KzRidFRvTzJybzBUVlJPRkgr
            anVJRUZaN1paRHVSc0JxdW94TmpmbUkKNLG3NS7c3Zp8BnTQoF01B1M+gym3GBWC
            k2USV67Y8TzTyxUjFzFnk418ExZyxVl7NQDvN0ZNKoeviuoHAHATKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T22:10:56Z"
    mac: ENC[AES256_GCM,data:wMlHPdYAglhahtZAkGtfHsJcp+HUI6MGhLlK1cUF5gejwTkOnHE/eqjXDnWlUj4QtM3ruSKN1CET6gvqFYSxPBLJVyo3cevk6/zizqLx/VWfXQzGWlOrC5aQjnFP7IGuRIvrJvW3phmF7YfAnY+p9zpVuTndqlApdMwbuYMGBxM=,iv:4Hhmb4+t4PyOqSUXlA4965GZyzOYpIxskS0T3IeYw84=,tag:INWab4mjg0sAB2N/wg386w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
