apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:v2GfS3dzOA0PpKBySxVmP/dC4sg=,iv:Qy26GEbBWx/0UQP8bHecAHjfOrHmb4xb+fWSYRhdD8c=,tag:8cJXrqpSY/VQ8k8YU6rz8w==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:Bf1x5cOb1PQupBDt+CaKhnkQLGY+/SFJ,iv:MslXCAEPijki8rXZKAN505aBt10+LR8ub8izcOD+WaQ=,tag:G4KLX5qg0p8jXc0VoocfKw==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:B/Y0KQRdHLkYw1CDgj9w94JXUXwpd0JK,iv:9GtJ9tuEhVIb1yjsXzDeJr+kynj+xtOuWF82N/fk74k=,tag:/s8gfDhF0e1klEFFKP1a9g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age18pglxfcmalplgnkpzg5v7mg9mqjwkmmc8gxjecat4j5mp5qtpgsqj6x9kq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZnhZejRDNUxLSHBkcFp2
            QWZxeWNHQytPclVwN2svRGdTdUgzS2t2L2c0CnYxRko1QjQvc0h5MXoycGo5MEd4
            WUpoNTRrbTJ0aUppM0dVYng5NEI0NVUKLS0tIHZXMWVzYnFRSXpialNZUk1RTUdz
            OFhOelhOT1RvODBpcXFBWU5IZlF1ejAK2q2ZYm4XZhWQwlI39kAGr2S4+m5ix27E
            LflzPN64W28Z8LFoaSLHP+WeM6RXvy1FDuK3YhjFr7RgC9b5wTTATA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T17:04:30Z"
    mac: ENC[AES256_GCM,data:3iPVWjOANAcvXtHYEC1UGTm4ITCUra5lpt7GG9G8iVqrAsuUQ7pY8B8x8xbW3axnINrrs1YqruNKP+YzPvBTZTlyu+y7b16afmh7tAVXzy+kl6fhw+NPPlCeqi+P/1875eQVmxxg9oBwdutw66b8/EwWUvrXHa/L27TaXa+ZxAg=,iv:Diur8nzZmD+nSRcSyMa0oAz1v/mYUKTTfnfT7iOqD/M=,tag:ghf7k9GgchPhThQZiDi5qg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
