apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:MqKnMwszLWdoysMrSUNkjVuqJTQ=,iv:clU+DO0xHRoaQsh9KPIkFQGhWyyoHGmLOWCmHG2w/kE=,tag:0QULxr8zqSQ2T1Atwqn0Gg==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:hkNVqMvJMxidjCxb0EWxn5woTBET1e9m,iv:tMAWy6kgk007zFCf69Q4ioWGJyF11tKyMoP9pnZzqA8=,tag:qs3pU7sV6uAwQDBe+kJbYw==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:BgHLJo+wYQW12h+uNaqTX4SPgdfgCNBh,iv:kZGap1loUuW/f0wpoC0YbLdEg8lzBAnawiX1a9ERs/Q=,tag:EeXiyPVAQQSoK3WhxUqDAg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age18pglxfcmalplgnkpzg5v7mg9mqjwkmmc8gxjecat4j5mp5qtpgsqj6x9kq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOT3NreU8zS2F4RTYvSEV5
            SURzNlBGdmlqRUJTWC9ZUWZHVGN3eTVGbUVRClBWODYyalZPam96ZHZ3aDdrNy9w
            SWlaaFpmbmtNRkVHQ1Y1c0RSOTUrUUkKLS0tIGhadVU0Mk5TV2tjKzd2MUR2VG9W
            SEd0cU9XVGV1ZURXUDlWMEg5SkFqZVEKGaXVvt+2WxjBjlmy66lDbe/H8IPs2ojy
            EjMVKlh2GqYxAMZNKgxBJmVVv0vmil0G1ymvoEdmNC3xTlYeR/+O+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T17:13:08Z"
    mac: ENC[AES256_GCM,data:ssvPn1yCYPngBFsElRv/3MhRI7XCBcMQyZG7i48xQZ1DHTUXgFfVj6jrg6tQUWBWWr5uITRWpziFX7rFmUDnhZlKq/DL5TJx1AafU9hmEO3h0xWxNfw5u4Io3hqiCOU14g1LpejMUsVaaT1DwV1aqJGu1/1zPbHc5IPajMjvwkA=,iv:jsT07U5bkyMY+2jFyfAfJ36lhPOdXArBWi+67kbeLgI=,tag:cEcqnq1PEWBgLOIbkSZwxQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
