apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:TTcatUOyVjN61zVSYcRSr8y5IJ4=,iv:VtQQyJGgel9mlyLsBrw2FXp/NVgeH20N8IO3RYFWQ+s=,tag:VPgFkCVmBI3AWPvll8CynQ==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:ZkTMdkdGHUkXXS9JX84cix91FVHqnVir,iv:hIpMDcYwKraxUHP9+vB/y+2S6V4McqzZGo84jDraExI=,tag:LGxbDdWaRgdwwONrrsM5BA==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:gtnA1PouU9SoOi0sy4pFYITIz5UwBwdp,iv:bmms2gutXY2ZHrSN1moDxixmTAQBz3hrV+Fppdt1/Ps=,tag:vOeRT/jq6tm8wswjun6/Mw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age18pglxfcmalplgnkpzg5v7mg9mqjwkmmc8gxjecat4j5mp5qtpgsqj6x9kq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhN1FNSDQwUURvK2xYQTFZ
            ZC8rV2NjbE9ITzBMbFpDclVoWW1pUTRsQjJzClh5Qm5FdkNBYzQzbkNIdFNFUTNq
            cXBEVUZkbmVqZHZvUi8xQjVDNlllM0kKLS0tIGw4c2ZJdUZIZndSM1dGMXdjc21o
            UGhBL25TL1d2VWVhd3NqTFZNN1ZwdEkKDdr5Z/ubyyi5eAIeP3XL4QGq0Q22/RMe
            Sq037L8SSwFzsGaQoAtfJWrbGnQD1YXMjuhZpEaNHLNi26IH+kO3Mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T16:27:05Z"
    mac: ENC[AES256_GCM,data:WDfnE30a2OX1JBxV6rgTi8rI79yEhdNKFCIYz2kYp1rMxW3gNrk/h7B9RcSe0vDqyhwF+b4tUx6biIEuJzAqHuo7Ig1SBzI6jq88nT4InHoba6Tf8sLD3AXYQVbxZzgZkaMi8cSms3VJUCxSECamYtfPsL2S5LE3bgUcPGZLwwE=,iv:yk2rj3ZOjsXInqXqP13APBL+IgguFmEk7tjZZcOy6OU=,tag:/zhMh7k1ftJh2SLEPTcHNw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
