apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: helm-repos
  namespace: flux-system
resources:
  - bjw-s.yaml
  - cloudnative-pg.yaml
  - home-ops-mirror.yaml
  - jetstack.yaml
  - kustomization.yaml
  - prometheus-community.yaml
  - spegel.yaml
  - truecharts.yaml
  - kubernetes-sigs-metrics-server.yaml
  - stakater.yaml
  - kyverno.yaml
  - weave-gitops.yaml
  - metallb.yaml
  - cilium.yaml
  - headlamp.yaml
  - ingress-nginx.yaml
